#!/bin/bash -l

# Specify job related parameter settings
#$ -P camplab
#$ -pe omp 12
#$ -M klgeyer@bu.edu
#$ -m beas
#$ -l h_rt=100:00:00
#$ -j y
#$ -V

# Load all dependencies
module load gcc

# Set environment variables
export HDF5_USE_FILE_LOCKING=FALSE

# Set directories
datadir=/restricted/projectnb/camplab/projects/MM-LDA/simulation-testing/data
codedir=/restricted/projectnb/camplab/home/klgeyer/gitlab/topic-models/code
modeldir=/restricted/projectnb/camplab/projects/MM-LDA/simulation-testing/models
resultdir=/restricted/projectnb/camplab/projects/MM-LDA/simulation-testing/results

# Configure Conda and pyMC3 environment
# 1. find conda installation
condash=/restricted/projectnb/camplab/home/klgeyer/miniconda3/etc/profile.d/conda.sh
# 2. name of pyMC3 environment
PMC3_ENV=pm3

# Define the number of replications or simulations for test
nreps=3
ncores=12

# Python test parameters
draws=1500             # number of sampling draws for MCMC
tune=1500             # number of tuning draws for MCMC
visampsize=100        # number of VI samples
nchain=4               # number of MCMC chains
viiters=30000         # number of VI iterations

# Run models in Python
source $condash
conda activate $PMC3_ENV
python lda_test.py $datadir $modeldir $resultdir $nreps $ncores $draws $tune $visampsize $nchain $viiters
conda deactivate
