#!/bin/bash -l

# Specify job related parameter settings, omp must be a mutliple of the number of chains
#$ -P camplab
#$ -pe omp 8
#$ -M youremail
#$ -m beas
#$ -l h_rt=50:00:00
#$ -j y

# Load all dependencies
module load gcc
module load R/4.0.0

# Set environment variables
export HDF5_USE_FILE_LOCKING=FALSE

# Set directories
datadir=yourpath
codedir=yourpath
modeldir=yourpath
resultdir=yourpath

# Data generation parameters
K=5
D=50
I=30
J=30
lam=200

# Define the number of relications or simulations for test
nreps=1
ncores=8

# R test parameters
mcmciters=1000
nchain=4               # number of MCMC chains
viiters=10000         # number of VI iterations

# Generate data
Rscript generate_data.R $codedir $datadir $nreps $ncores $K $D $I $J $lam

# Run models in R
outfn=$codedir/RStan-LDA-tests/lda_test_result_$JOB_ID.out
Rscript lda_test.R $codedir $datadir $modeldir $nreps $ncores $nchain $viiters $mcmciters $out_fn
